### ISSUE TITLE
Feature request: Language detection for Finnish and Swedish

### ISSUE THREAD

**Issue by osma** [NationalLibraryOfNorway/meteor#4]
The current language detection works only on a few languages used in Norway.

Could you please add models for detecting Finnish and Swedish as well? I understood that these exist elsewhere and just need to be copied to this project.

Thanks!

**Comment by pierrebeauguitte** [comment]
Now that we have replaced our previous language detection module with [langdetect](https://pypi.org/project/langdetect/), Finnish and Swedish languages should be recognized properly.
Once we find a proper way to reintegrate the previous models, that are optimized for Nordic languages, we will make sure to keep supporting Finnish and Swedish (and more).

**Comment by osma** [comment]
Perfect, thanks a lot @pierrebeauguitte !
