### ISSUE TITLE
Clarify license: Apache vs. GPL

### ISSUE THREAD

**Issue by osma** [NationalLibraryOfNorway/meteor#5]
The top level [LICENSE file](https://github.com/NationalLibraryOfNorway/meteor/blob/main/LICENSE) states that the code is under Apache 2.0 license. Howewer, the language detector code [pytextcat.py](https://github.com/NationalLibraryOfNorway/meteor/blob/main/language/pytextcat.py) is apparently copied from elsewhere and the comment header states that it is under the GPL.

In my understanding, including GPL code as a core part of a software package implies that the GPL terms apply to the whole codebase.

The situation should be clarified. I can see a few options:

1. Change the overall license of Meteor to GPL.
2. Declare that the Meteor codebase (excluding pytextcat) is still under Apache 2.0 license, but in practice, the GPL terms apply to the whole. (Then in principle, someone could copy non-pytextcat parts of the code and use it elsewhere according to the terms of the Apache license without being bound by the GPL.)
3. Switch to some other language detector implementation that is not GPL licensed.
4. Make it possible to use different language detector implementations so that using pytextcat becomes optional and thus it is no longer a core part of Meteor. (This is how Annif, which also is under the Apache 2.0 license, uses the GPL licensed library YAKE - it is an optional dependency, you can use Annif without YAKE. See the [note about licensing](https://github.com/NatLibFi/Annif#license) in the Annif README)

**Comment by pierrebeauguitte** [comment]
Hi Osma,

Thank you once again for pointing this out to us, we are on the case.
Option (4) seems like a very good choice. Until we find a good way to integrate our current classifier as an optional dependency, I have opened a PR that replaces it with another python module (langdetect), that might also give you better results in Swedish and Finnish!
